
- hosts: localhost
  tasks:
  - name: STOP Application
    import_playbook: stop-application.yml
  - name: Delete environment
    import_playbook: delete-env.yml
  
- hosts: all
  tasks: 
  - name: cleaning all {{appli_prdocc}}
    shell: rm -rf /users/{{appli_prdocc}}/*
    ignore_errors: yes